<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="800683" started-at="2020-05-11T18:15:26Z" finished-at="2020-05-11T18:28:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="800683" started-at="2020-05-11T18:15:26Z" finished-at="2020-05-11T18:28:47Z">
      <class name="twc.Regression.TestCases.regressionTestCases">
        <test-method status="PASS" signature="Before_Test()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="Before_Test" is-config="true" duration-ms="458015" started-at="2020-05-11T23:45:26Z" finished-at="2020-05-11T23:53:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before_Test -->
        <test-method status="FAIL" signature="C333216_Verify_cust_param_cnd()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="C333216_Verify_cust_param_cnd" duration-ms="333455" started-at="2020-05-11T23:53:05Z" finished-at="2020-05-11T23:58:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[cnd Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: cnd Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:191)
	at twc.Regression.TestCases.regressionTestCases.C333216_Verify_cust_param_cnd(regressionTestCases.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333216_Verify_cust_param_cnd -->
        <test-method status="PASS" signature="C333202_Verify_cust_param_zip()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="C333202_Verify_cust_param_zip" duration-ms="3402" started-at="2020-05-11T23:58:38Z" finished-at="2020-05-11T23:58:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333202_Verify_cust_param_zip -->
        <test-method status="FAIL" signature="C333213_Verify_cust_param_adid()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="C333213_Verify_cust_param_adid" duration-ms="2853" started-at="2020-05-11T23:58:41Z" finished-at="2020-05-11T23:58:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[adid Value not matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: adid Value not matched
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Regression.TestCases.Custom_Parameters_Verification.parameters_Verification(Custom_Parameters_Verification.java:510)
	at twc.Regression.TestCases.regressionTestCases.C333213_Verify_cust_param_adid(regressionTestCases.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C333213_Verify_cust_param_adid -->
        <test-method status="PASS" signature="C658712_Verify_cust_param_plat()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="C658712_Verify_cust_param_plat" duration-ms="2906" started-at="2020-05-11T23:58:44Z" finished-at="2020-05-11T23:58:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- C658712_Verify_cust_param_plat -->
        <test-method status="PASS" signature="After_Test()[pri:0, instance:twc.Regression.TestCases.regressionTestCases@7210f559]" name="After_Test" is-config="true" duration-ms="0" started-at="2020-05-11T23:58:47Z" finished-at="2020-05-11T23:58:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After_Test -->
      </class> <!-- twc.Regression.TestCases.regressionTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
